Adi8080/Hactoberfest2021

Java_DSA/JavaRecursionRepPrograms.txt
Java_DSA/Recursion/BoardPath.java
Java_DSA/Recursion/GetPermutation.java
Java_DSA/Recursion/GetSubsequences.java
Java_DSA/Recursion/MazePath.java
Java_DSA/Recursion/MergeSort.java
Java_DSA/Recursion/MergetwoSortArray.java
Java_DSA/Recursion/NQueensProblem.java
Java_DSA/Recursion/PowerinLogn.java
Java_DSA/Recursion/PrintBoardPath.java
Java_DSA/Recursion/PrintMazePath.java
Java_DSA/Recursion/PrintNQueen.java
Java_DSA/Recursion/PrintPermutations.java
Java_DSA/Recursion/PrintRecursionSubsequences.java
Java_DSA/Recursion/QuickSort (2).java
Java_DSA/Recursion/QuickSort.java
Java_DSA/Recursion/SeiveofErothesis-PrimeNo..java
Java_DSA/Recursion/Sort0s1s2sarray.java

Recursion Problems Java DSA. If you found any conflicts do let me know.

Recursion Problems Java DSA

---

ExpressionValidityUsingStack.c

Merge my contribution for Hacktoberfest

Added C program to validate expression using STACK

---

linkedlistreversal.cpp

easiest program for linked list reversal

---

LoopDetectionInLinkedList.cpp

Added Loop Detection in a Singly Linked List

---

Java_DSA/Recursion/Print Stair Paths.java

I have added a question "Print Stair Paths".
1. You are given a number n representing number of stairs in a staircase.
2. You are standing at the bottom of staircase. You are allowed to climb 1 step, 2 steps or 3 steps in one move.
3. Complete the body of printStairPaths function - without changing signature - to print the list of all paths that can be used to climb the staircase up.
Use sample input and output to take idea about output.
(I've also commented code in the question.

Create Print Stair Paths.java

---

C_CPP_DSA/Algorithms/Sorting/insertion sort

Create insertion sort

---

Java_DSA/Recursion/knights_tour.java

A very good problem to know the insights of recursion

knights_tour.java

---

Java_DSA/CylindricalRotate.java

I have added JAVA Code for Cylindrical Rotation of array elements.

CylindericalRotate.java

---

Java_DSA/Kthsmallestnumber.java

I have added JAVA Code for finding the smallest element at Kth position.

Kthsmallestnumber Java code

---

Java_DSA/KadaneAlgorithm.java

I have added JAVA Code for Kadane's Algorithm.

Kadane Algorithm

---

Java_DSA/Sorting/MergeSort.java

MergeSort Java DSA

---

Java_DSA/ListNode.java
Java_DSA/Sorting/Radix.java

Hey There, I have contributed with 2 Java Programs:
1) Add 2 Numbers(Linked List)
2) Radix Sort

Java Programs

---

Java_DSA/Reverse_Arrayelement.java

I have added JAVA Code for reverse of an array elements by using Efficient Approach with Time Complexity of theta(n).

Reverse_Arrayelement.java

---

Java_DSA/Buy_Sell_Stock.java

I have added JAVA Code for Buy Sell Stock in Java.

Buy_Sell_Stock.java

---

C_CPP_DSA/Algorithms/Sorting/DNF_Sort.cpp
C_CPP_DSA/Algorithms/Sorting/Wave_Sort.cpp

Added Wave Sort and Dutch National Flag Sorting Algorithm

Added Other Algorithms

---

C_CPP_DSA/Stack/DoubleChar_Stacks.cpp

Added DoubleChar_Stacks.cpp

---

Java_DSA/Sorting Algorithms/Insertion_Sort

Insertion_Sort

---

Java_DSA/Sorting Algorithms/Quick_Sort

Added Quick Sort Algorithm in java

Quick_Sort

---

Josephus Problem/josephus.cpp

A very standard Josephus Problem

Added Josephus Problem Solution in CPP

---

C_CPP_DSA/Algorithms/prims.cpp

added prims algorithm to your file

created prims.cpp

---

Python_DSA/add_number_LL.py

Add two very large-sized numbers represented as a linked list in a reverse manner.
Driver codes and util functions as also added.
Leetcode Medium LL

Add two big numbers represented as linked lists

---

Java_DSA/graphs/dijkstraAlgo.java

Graphs- Dijkstra algo added

---

Java_DSA/graphs/kruskal.java

kruskal algo added in graphs

---

Python_DSA/Sorting/counting_sort.py
Python_DSA/Sorting/radix_sort.py

Added Counting and Radix sort contribution for Hacktoberfest 2021
Github Profile :  https://github.com/HarshOza36

Counting and Radix Sort added in Sorting Python DSA

---

searchinAndSorting/Cocktail_Sort.py

Cocktail_sort

---

DynamicProgramming/MinimisingCoins.cpp

Number f coins to be minimum for making a particular sum

Minimizing Coins problem

---

bmi_calculator.py

bmi_calculator.py

---

Array Question in C++/fibbRecursion.cpp

hey! @Adi8080, I know I am a bit late,
Please merge it ASAP,
added a program to find Fibonacci using recursion in array

added a program to find fibonacci using recursion
